In [1]:
import pandas as pd
from src.config import DATA_DIR

ligand_df = pd.read_csv(f'{DATA_DIR}/metadata/CROWN_ligand_data.csv')
pdb_df = pd.read_csv(f'{DATA_DIR}/metadata/pdb_metadata.csv')
pli_df = pd.read_csv(f'{DATA_DIR}/metadata/pli_filter_pass.csv')
uniprot_df = pd.read_csv(f'{DATA_DIR}/metadata/cath_full.csv')
special_residues = pd.read_csv(f'{DATA_DIR}/metadata/special_residues.csv')

In [2]:
ligand_df.head()

,basename,MW,HeavyAtoms,N+O_Atoms,HBD,HBA,RotatableBonds,NumRings,TPSA,QED,SMILES,MurckoScaffold
0,3zwe_F,650.580,44.0,20.0,13.0,20.0,9.0,4.0,327.60,0.1101,C[C@@H]1O[C@@H](O[C@H]2[C@H](O[C@H]3[C@H](O)[C...,C1CC[C@@H](O[C@H]2CCO[C@@H](O[C@H]3CCCOC3)[C@@...
1,7gnu_I,521.042,36.0,7.0,0.0,5.0,4.0,6.0,94.37,0.5078,N#CC1(CS(=O)(=O)N2Cc3ccc(Cl)cc3[C@@]3(CCCN(c4c...,O=C1N(c2cncc3ccccc23)CCC[C@]12CN(S(=O)(=O)CC1C...
2,6c58_G,534.260,34.0,18.0,6.0,17.0,8.0,3.0,282.42,0.1697,O=c1ccn([C@@H]2O[C@H](CO[P@@](=O)([O-])O[P@@](...,O=c1ccn([C@H]2CC[C@@H](CO[PH](=O)O[PH](=O)O[C@...
3,5g6q_E,293.350,22.0,5.0,2.0,4.0,5.0,3.0,75.00,0.6901,C=[NH+]Cc1cncc(OCc2ccc3ccc(N)nc3c2)c1,c1cncc(OCc2ccc3cccnc3c2)c1
4,3t9b_B,502.166,31.0,18.0,4.0,17.0,8.0,3.0,293.25,0.2468,Nc1ncnc2c1ncn2[C@@H]1O[C@H](CO[P@](=O)([O-])O[...,c1ncc2ncn([C@H]3CCCO3)c2n1

In [3]:
pdb_df.head()

  pdb_id  resolution  r_free
0   101d       2.250  0.2520
1   107l       1.800     NaN
2   10ia       1.739  0.2277
3   10ra       1.790  0.2387
4   113l       1.800     NaN

In [4]:
pli_df.rename(columns = {'filename': 'basename'}, inplace = True)
pli_df.head()

,basename,lig_name,sas_ratio,ligand_rsr,ligand_rscc,pocket_rsr,pocket_rscc,chain_set
0,6gpo_B,CMP,0.996566,0.044,0.977,0.056042,0.970458,B-A
1,6tu6_FA,6NT,1.000000,0.027,0.994,0.026200,0.995640,FA-F
2,6tu6_TA,6NT,1.000000,0.018,0.997,0.018120,0.997480,TA-M
3,6tu6_WA,6NT,1.000000,0.031,0.993,0.027280,0.995240,N-WA
4,6tu6_QA,6NT,1.000000,0.023,0.995,0.025240,0.996040,QA-K

In [5]:
df = ligand_df.merge(pli_df, how = 'inner', on = ['basename'])
print(len(ligand_df))
print(len(df))

155505
155505

In [6]:
df['pdb_id'] = df['basename'].str[:4]
df = df.merge(pdb_df, how = 'inner', on = ['pdb_id'])
print(len(df))

155505

In [7]:
df.head()

,basename,MW,HeavyAtoms,N+O_Atoms,HBD,HBA,RotatableBonds,NumRings,TPSA,QED,...,lig_name,sas_ratio,ligand_rsr,ligand_rscc,pocket_rsr,pocket_rscc,chain_set,pdb_id,resolution,r_free
0,3zwe_F,650.580,44.0,20.0,13.0,20.0,9.0,4.0,327.60,0.1101,...,BGC-GAL-FUC-GLA,0.914696,0.06425,0.9395,0.063531,0.943812,F-C,3zwe,1.750,0.26579
1,7gnu_I,521.042,36.0,7.0,0.0,5.0,4.0,6.0,94.37,0.5078,...,S7U,0.873392,0.09300,0.9450,0.089741,0.929741,A-G-B-I,7gnu,1.480,0.24510
2,6c58_G,534.260,34.0,18.0,6.0,17.0,8.0,3.0,282.42,0.1697,...,UDX,0.975661,0.07300,0.9600,0.088412,0.936618,A-G,6c58,2.198,0.24440
3,5g6q_E,293.350,22.0,5.0,2.0,4.0,5.0,3.0,75.00,0.6901,...,TUE,0.975553,0.06400,0.9510,0.067300,0.949850,A-B-E-C,5g6q,2.030,0.21550
4,3t9b_B,502.166,31.0,18.0,4.0,17.0,8.0,3.0,293.25,0.2468,...,ANP,0.993143,0.03600,0.9870,0.064258,0.950548,B-A,3t9b,1.850,0.21100

In [8]:
special_residues.rename(columns = {'CCD': 'lig_name'}, inplace = True)
special_residues

,lig_name,MW,HeavyAtoms,N+O_Atoms,HBD,HBA,RotatableBonds,NumRings,TPSA,QED,SMILES,MurckoScaffold
0,HEM,616.499,43,8,2,6,8,6,96.26,0.417,C=CC1=C(C)C2=Cc3c(C)c(CCC(=O)O)c4[n]3[Fe]35<-[...,C1=CC2=[N]3->[Fe]45<-[N]6=C(C=CC6=Cc6ccc([n]64...
1,MGD,740.567,47,23,12,21,9,6,346.63,0.083,Nc1nc2c(c(=O)[nH]1)N[C@H]1C(S)=C(S)[C@@H](CO[P...,O=c1[nH]cnc2c1N[C@H]1C=C[C@@H](CO[PH](=O)O[PH]...

In [9]:
df_new = df.merge(special_residues, on = 'lig_name', how = 'left', suffixes=("", "_new"))

for col_name in ['MW', 'HeavyAtoms', 'N+O_Atoms', 'HBD', 'HBA', 'RotatableBonds', 'NumRings', 'TPSA', 'QED', 'SMILES', 'MurckoScaffold']:
    df_new[col_name] = df_new[f'{col_name}_new'].combine_first(df_new[col_name])
    df_new.drop(columns = [f'{col_name}_new'], inplace = True)

In [10]:
df = df_new.copy()
df.head()

,basename,MW,HeavyAtoms,N+O_Atoms,HBD,HBA,RotatableBonds,NumRings,TPSA,QED,...,lig_name,sas_ratio,ligand_rsr,ligand_rscc,pocket_rsr,pocket_rscc,chain_set,pdb_id,resolution,r_free
0,3zwe_F,650.580,44.0,20.0,13.0,20.0,9.0,4.0,327.60,0.1101,...,BGC-GAL-FUC-GLA,0.914696,0.06425,0.9395,0.063531,0.943812,F-C,3zwe,1.750,0.26579
1,7gnu_I,521.042,36.0,7.0,0.0,5.0,4.0,6.0,94.37,0.5078,...,S7U,0.873392,0.09300,0.9450,0.089741,0.929741,A-G-B-I,7gnu,1.480,0.24510
2,6c58_G,534.260,34.0,18.0,6.0,17.0,8.0,3.0,282.42,0.1697,...,UDX,0.975661,0.07300,0.9600,0.088412,0.936618,A-G,6c58,2.198,0.24440
3,5g6q_E,293.350,22.0,5.0,2.0,4.0,5.0,3.0,75.00,0.6901,...,TUE,0.975553,0.06400,0.9510,0.067300,0.949850,A-B-E-C,5g6q,2.030,0.21550
4,3t9b_B,502.166,31.0,18.0,4.0,17.0,8.0,3.0,293.25,0.2468,...,ANP,0.993143,0.03600,0.9870,0.064258,0.950548,B-A,3t9b,1.850,0.21100

In [11]:
# Now merge with UniProt entries
uniprot_df.drop_duplicates(subset = ['pdb_id', 'chain_id'], keep = 'first', inplace = True)
uniprot_df.head()

,pdb_id,chain_id,uniprot_id,taxon_id,species_name,entry_name,GO_ids,protein_name,EC_number,cath_ids
0,101m,A,P02185,9755.0,Physeter macrocephalus,MYG_PHYMC,GO:0004601_GO:0005344_GO:0016528_GO:0019430_GO...,Myoglobin (Nitrite reductase MB) (EC 1.7.-.-) ...,1.11.1.-_1.7.-.-,1.10.490.10
1,102l,A,P00720,10665.0,Tequatrovirus T4,ENLYS_BPT4,GO:0003796_GO:0009253_GO:0016998_GO:0030430_GO...,Endolysin (EC 3.2.1.17) (Lysis protein) (Lysoz...,3.2.1.17,1.10.530.40
3,102m,A,P02185,9755.0,Physeter macrocephalus,MYG_PHYMC,GO:0004601_GO:0005344_GO:0016528_GO:0019430_GO...,Myoglobin (Nitrite reductase MB) (EC 1.7.-.-) ...,1.11.1.-_1.7.-.-,1.10.490.10
4,103l,A,P00720,10665.0,Tequatrovirus T4,ENLYS_BPT4,GO:0003796_GO:0009253_GO:0016998_GO:0030430_GO...,Endolysin (EC 3.2.1.17) (Lysis protein) (Lysoz...,3.2.1.17,1.10.530.40
6,103m,A,P02185,9755.0,Physeter macrocephalus,MYG_PHYMC,GO:0004601_GO:0005344_GO:0016528_GO:0019430_GO...,Myoglobin (Nitrite reductase MB) (EC 1.7.-.-) ...,1.11.1.-_1.7.-.-,1.10.490.10

In [12]:
annot_cols = ['uniprot_id', 'taxon_id', 'species_name', 'entry_name',
              'GO_ids', 'protein_name', 'EC_number', 'cath_ids']

multi_cols = ['GO_ids', 'EC_number', 'cath_ids']  # underscore-joined sets

# Pre-split the multi-value columns in df_B into lists
df_B_proc = uniprot_df.copy()
for c in multi_cols:
    df_B_proc[c] = df_B_proc[c].fillna('').astype(str).str.split('_')


# 1. Explode chain_set into one row per (basename, pdb_id, chain_id)
exp = (df[['basename', 'pdb_id', 'chain_set']]
       .assign(chain_id=lambda d: d['chain_set'].str.split('-'))
       .explode('chain_id'))

# 2. Join annotations from df_B on (pdb_id, chain_id)
merged = exp.merge(df_B_proc[['pdb_id', 'chain_id', *annot_cols]],
                   on=['pdb_id', 'chain_id'], how='left')

# 3. Collapse to one row per basename, collecting unique values as sets
def to_set(s):
    out = set()
    for v in s.dropna():
        if isinstance(v, list):
            out.update(x for x in v if x != '')
        else:
            out.add(v)
    return out

agg = merged.groupby('basename')[annot_cols].agg(to_set)

# 4. Attach back to df_A
df = df.merge(agg, on='basename', how='left')

In [13]:
df.head()

,basename,MW,HeavyAtoms,N+O_Atoms,HBD,HBA,RotatableBonds,NumRings,TPSA,QED,...,resolution,r_free,uniprot_id,taxon_id,species_name,entry_name,GO_ids,protein_name,EC_number,cath_ids
0,3zwe_F,650.580,44.0,20.0,13.0,20.0,9.0,4.0,327.60,0.1101,...,1.750,0.26579,{Q0B4G1},{},{},{},{},{},{},{2.40.128.190}
1,7gnu_I,521.042,36.0,7.0,0.0,5.0,4.0,6.0,94.37,0.5078,...,1.480,0.24510,{P0DTD1},{2697049.0},{Severe acute respiratory syndrome coronavirus 2},{R1AB_SARS2},"{GO:0085034, GO:0006351, GO:0043139, GO:000017...",{Replicase polyprotein 1ab (pp1ab) (ORF1ab pol...,"{3.6.4.12, 2.7.7.48, 2.1.1.56, 2.7.7.50, 3.4.2...",{}
2,6c58_G,534.260,34.0,18.0,6.0,17.0,8.0,3.0,282.42,0.1697,...,2.198,0.24440,{O60701},{9606.0},{Homo sapiens},{UGDH_HUMAN},"{GO:0003979, GO:0005829, GO:0048666, GO:007006...",{UDP-glucose 6-dehydrogenase (UDP-Glc dehydrog...,{1.1.1.22},"{1.20.5.100, 3.40.50.720}"
3,5g6q_E,293.350,22.0,5.0,2.0,4.0,5.0,3.0,75.00,0.6901,...,2.030,0.21550,{O34453},{224308.0},{Bacillus subtilis subsp. subtilis str. 168},{NOSO_BACSU},"{GO:0004517, GO:0020037, GO:0006809, GO:0046872}",{Nitric oxide synthase oxygenase (EC 1.14.14.4...,{1.14.14.47},"{3.90.340.10, 3.90.1230.10, 3.90.440.10}"
4,3t9b_B,502.166,31.0,18.0,4.0,17.0,8.0,3.0,293.25,0.2468,...,1.850,0.21100,{O43314},{9606.0},{Homo sapiens},{VIP2_HUMAN},"{GO:0005524, GO:0005829, GO:0043647, GO:003295...",{Inositol hexakisphosphate and diphosphoinosit...,{2.7.4.24},"{3.40.50.11950, 3.30.470.20}"

In [14]:
set_cols = ['uniprot_id', 'taxon_id', 'species_name', 'entry_name',
            'GO_ids', 'protein_name', 'EC_number', 'cath_ids']

df_out = df.copy()
for c in set_cols:
    df_out[c] = df_out[c].apply(lambda x: sorted(x) if isinstance(x, set) else x)

df_out.to_parquet('annotated.parquet')

In [15]:
len(df_out)

155505